# ========== KẾT NỐI DATABASE POSTGRESQL ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/jwtdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========== SERVER ==========
server.port=8080

# ========== JWT ==========
bezkoder.app.jwtSecret=VGhpc0lzQVNlY3VyZUtleUZvckp3dEdlbmVyYXRpb24xMjMh
bezkoder.app.jwtExpirationMs=86400000
